### ISSUE TITLE
Improve results jumpiness

### ISSUE THREAD

**Issue by adamschwartz** [VectorLogoZone/logosearch#2]
Following up on https://news.ycombinator.com/item?id=23520829

> **the_duke**
> Looks useful.
>
> Feedback: the result rendering is very "jumpy" due to logos loading in one at a time.
>
> You could either render sized wrapper containers for each logo, or load them in in the background and only show them once ready (with a loading indicator somewhere).
>
> > **Fileformat**
> > I have tried various solutions, but nothing that works better than what's there now.
> >
> > I only force the height for the logos, not the width, so wrapping doesn't really improve things.
> >
> > Waiting to display until they are all loaded kills the "instant" tagline. I'm hotlinking the images, so some images can take awhile.

I agree that there’s a value in loading the images as they come in, rather than waiting for them all to load before displaying any. But I think there is something else you could do which would help a lot.

One source of jumpiness is the fact that images have a `6px` border around them as well as a `1px` border.

```
.logo-container img {
  box-shadow: 0 0 5px #1d1d1d;
  border: solid #ccc 1px;
  margin: 6px;
}
```

This means that the UI paints many intermediate frames with dozens of little rectangular boxes in it, as the images are loading in:

![logo search search example gif](https://user-images.githubusercontent.com/154613/85467943-cfc9ca80-b579-11ea-8b3b-5646a5aa198c.gif)

Here are a couple frames pulled from that sequence:

![image](https://user-images.githubusercontent.com/154613/85467304-0b17c980-b579-11ea-908b-086b75693b3c.png)

![image](https://user-images.githubusercontent.com/154613/85468003-e2440400-b579-11ea-8571-c508aecf1f1a.png)

----------------------------------------

My recommendation for fixing this would be insert the images into the DOM after they are loaded.

Additionally, I’d recommend adding the images in the order they load, as this would prevent images from getting "bumped" down as new ones are loaded before them.

Something like this:

```js
const resultsEl = document.querySelector('#search_results")
const results = [/* array of strings of `src`s of images */]

results.forEach(src => {
  const img = new Image()
  img.onload = () => resultsEl.appendChild(img)
  img.src = src
})
```

I hope this helps!

**Comment by fileformat** [comment]
Thanks for the detailed feedback!

Since the results are search results, they do have a specific order, so I can't insert them as they are loaded.

I added a css `loading` class for the images & remove it when they load/error.  I tried a few variations, and the one I like best is a fixed width + a spinner.  The fixed width really cuts down on the jumpiness (IMHO anyway).

Note that I only do it for dynamically inserted images.  The site works with JavaScript disabled, so server-side results (which include the initial page load of random logos) are still pretty jumpy.
